version: "3"
services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - /path/to/your/persistent/data:/var/lib/mysql
    ports:
      - "9999:3306"
    restart: always